export const qryFindDataQr = `SELECT a.BARCODE_SERIAL, h.BUNDLE_SEQUENCE, a.SCH_ID,  b.BUYER_CODE, b.SITE_LINE SITE_LINE_FX, g.CUT_SITE_NAME SITE_NAME, e.LINE_NAME,
b.ORDER_NO, b.MO_NO, f.ORDER_REFERENCE_PO_NO ORDER_REF, f.ITEM_COLOR_NAME ORDER_COLOR, b.ORDER_STYLE, b.ORDER_SIZE, 
b.ORDER_QTY, DATE(a.CUT_SCAN_TIME) SCAN_DATE, TIME(a.CUT_SCAN_TIME) SCAN_TIME
FROM scan_supermarket_in a
LEFT JOIN order_detail b ON a.BARCODE_SERIAL = b.BARCODE_SERIAL 
LEFT JOIN cuting_loading_schedule g ON a.CUT_ID = g.CUT_ID
LEFT JOIN viewcapacity f ON f.ID_CAPACITY = g.CUT_ID_CAPACITY
LEFT JOIN item_siteline e ON e.ID_SITELINE = g.CUT_ID_SITELINE
LEFT JOIN order_qr_generate h ON  h.BARCODE_SERIAL = a.BARCODE_SERIAL
WHERE a.BARCODE_SERIAL =  :barcodeserial`;

export const qryTrackOneDetail = ` SELECT 
n.PROSES,
n.BARCODE_SERIAL,
n.SPLIT_QR,
n.PROSES_TIME,
n.PROSESS_BY
FROM (
    SELECT 'GENERATE/PRINT' AS PROSES,  a.BARCODE_SERIAL,'-' SPLIT_QR,    a.CREATE_TIME AS PROSES_TIME, b.USER_NAME PROSESS_BY
    FROM order_qr_generate a 
    LEFT JOIN xref_user_web b ON b.USER_ID = a.CREATE_BY
    WHERE a.BARCODE_SERIAL = :barcodeserial 
    UNION ALL
    SELECT 'SUPERMARKET IN' AS PROSES, a.BARCODE_SERIAL, '-' SPLIT_QR,    a.CUT_SCAN_TIME AS PROSES_TIME, b.USER_NAME PROSESS_BY
    FROM scan_supermarket_in a 
    LEFT JOIN xref_user_web b ON b.USER_ID = a.CUT_SCAN_BY
    WHERE a.BARCODE_SERIAL = :barcodeserial
    UNION ALL
    SELECT  'SUPERMARKET OUT' AS PROSES, a.BARCODE_SERIAL,  '-' SPLIT_QR,  a.CUT_SCAN_TIME AS PROSES_TIME, b.USER_NAME PROSESS_BY
    FROM scan_supermarket_out a
    LEFT JOIN xref_user_web b ON b.USER_ID = a.CUT_SCAN_BY
    WHERE a.BARCODE_SERIAL = :barcodeserial
    UNION ALL
    SELECT 'SEWING IN' AS PROSES,  a.BARCODE_SERIAL, '-' SPLIT_QR, a.SEWING_SCAN_TIME AS PROSES_TIME, b.USER_NAME PROSESS_BY
    FROM scan_sewing_in a 
    LEFT JOIN xref_user_web b ON b.USER_ID = a.SEWING_SCAN_BY
    WHERE a.BARCODE_SERIAL = :barcodeserial
    UNION ALL
    SELECT 'QR_RETURN' AS PROSES,  a.BARCODE_SERIAL, '-' SPLIT_QR, a.SEWING_SCAN_TIME AS PROSES_TIME, 
    b.QC_NAME PROSESS_BY
    FROM scan_sewing_return a 
    LEFT JOIN qc_inspection_user b ON b.QC_USER_ID = a.SEWING_RETURN_BY
    WHERE a.BARCODE_SERIAL = :barcodeserial
    UNION ALL 
    SELECT 'QR_SPLIT' AS PROSES,  a.BARCODE_MAIN AS BARCODE_SERIAL, 
    CASE WHEN a.BARCODE_SERIAL <> a.BARCODE_MAIN THEN a.BARCODE_SERIAL ELSE '-' END AS
    SPLIT_QR,  a.SEWING_SCAN_TIME AS PROSES_TIME, b.QC_NAME PROSESS_BY
    FROM scan_sewing_qr_split a 
    LEFT JOIN qc_inspection_user b ON b.QC_USER_ID = a.SEWING_SCAN_BY
    WHERE a.BARCODE_MAIN = :barcodeserial
    UNION ALL
    SELECT 'SEWING OUT' AS PROSES,  a.BARCODE_MAIN AS BARCODE_SERIAL, 
    CASE WHEN a.BARCODE_SERIAL <> a.BARCODE_MAIN THEN a.BARCODE_SERIAL ELSE '-' END AS
    SPLIT_QR,  a.SEWING_SCAN_TIME AS PROSES_TIME, b.QC_NAME PROSESS_BY
    FROM scan_sewing_out a 
    LEFT JOIN qc_inspection_user b ON b.QC_USER_ID = a.SEWING_SCAN_BY
    WHERE a.BARCODE_MAIN = :barcodeserial
    UNION ALL 
    SELECT 'PACKING IN' AS PROSES, a.BARCODE_MAIN AS BARCODE_SERIAL, 
    CASE  WHEN a.BARCODE_SERIAL <> a.BARCODE_MAIN THEN a.BARCODE_SERIAL ELSE '-' END AS SPLIT_QR,
    a.PACKING_SCAN_TIME AS PROSES_TIME, b.USER_NAME PROSESS_BY
    FROM scan_packing_in a 
    LEFT JOIN xref_user_web b ON b.USER_ID = a.PACKING_SCAN_BY
    WHERE a.BARCODE_MAIN = :barcodeserial
) n`;

export const qryFindHisQrOutput = `SELECT a.BARCODE_SERIAL,
a.ENDLINE_OUT_TYPE,
CASE WHEN a.ENDLINE_PORD_TYPE = 'N' THEN 'NORMAL'
WHEN a.ENDLINE_PORD_TYPE = 'O' THEN 'OVERTIME' 
ELSE 'EXTRA OVERTIME' END AS ENDLINE_PORD_TYPE, 
a.ENDLINE_OUT_QTY, 
a.ENDLINE_MOD_TIME,
a.ENDLINE_OUT_UNDO,
b.QC_NAME
FROM qc_endline_output a 
LEFT JOIN qc_inspection_user b ON b.QC_USER_ID = a.ENDLINE_ADD_ID
WHERE a.BARCODE_SERIAL = :barcodeserial `;
