export const queryMasterProductIDGMT = `
SELECT
	mii.ITEM_ID,
	mii.ITEM_CODE,
	mii.ITEM_DESCRIPTION,
	pit.MASTER_ATTRIBUTE_VALUE_NAME AS PRODUCT_ITEM_TYPE,
	pic.MASTER_ATTRIBUTE_VALUE_NAME AS PRODUCT_ITEM_CATEGORIES,
	pi2.PRODUCT_ID 
FROM
	master_item_id mii
LEFT JOIN (
	SELECT
		miia.MASTER_ITEM_ID,
		miia.MASTER_ATTRIBUTE_ID,
		mas.NAME AS MASTER_ATTRIBUTE_NAME,
		miia.MASTER_ATTRIBUTE_VALUE_ID,
		mav.NAME AS MASTER_ATTRIBUTE_VALUE_NAME
	FROM
		master_item_id_attributes miia 
	LEFT JOIN master_attribute_setting mas ON mas.ID = miia.MASTER_ATTRIBUTE_ID 
	LEFT JOIN master_attribute_value mav ON mav.ID = miia.MASTER_ATTRIBUTE_VALUE_ID 
	WHERE mas.NAME = 'PRODUCT ITEM TYPE'
) AS pit on pit.MASTER_ITEM_ID = mii.ITEM_ID 
LEFT JOIN (
	SELECT
		miia.MASTER_ITEM_ID,
		miia.MASTER_ATTRIBUTE_ID,
		mas.NAME AS MASTER_ATTRIBUTE_NAME,
		miia.MASTER_ATTRIBUTE_VALUE_ID,
		mav.NAME AS MASTER_ATTRIBUTE_VALUE_NAME
	FROM
		master_item_id_attributes miia 
	LEFT JOIN master_attribute_setting mas ON mas.ID = miia.MASTER_ATTRIBUTE_ID 
	LEFT JOIN master_attribute_value mav ON mav.ID = miia.MASTER_ATTRIBUTE_VALUE_ID 
	WHERE mas.NAME = 'PRODUCT ITEM CATEGORIES'
) AS pic on pic.MASTER_ITEM_ID = mii.ITEM_ID 
LEFT JOIN product_item pi2 ON pi2.PRODUCT_TYPE_ATTB = pit.MASTER_ATTRIBUTE_VALUE_ID AND pi2.PRODUCT_CAT_ATTB = pic.MASTER_ATTRIBUTE_VALUE_ID 
WHERE mii.ITEM_ID LIKE 'GMT%'
`;