// import { DataTypes } from "sequelize";
import db from "../../config/database.js";

export const QryListSiteZd = `SELECT DISTINCT
zis.SITE, zis.SITE_NAME, zis.CUS_NAME, zis.SITE_NAME id, zis.SITE_NAME name
FROM zd_item_siteline zis
WHERE zis.ZD_STATUS  = 1`;

export const QryListLineZd = `SELECT  zis.SITE, zis.SITE_NAME, zis.CUS_NAME, zis.ID_SITELINE, zis.LINE_NAME,
zis.ID_SITELINE id, CONCAT(zis.SITE_NAME, ' - ', zis.LINE_NAME)  name 
FROM zd_item_siteline zis  WHERE zis.ZD_STATUS  = 1`;

export const QryPoNoSoruce = `SELECT a.SCH_ID, a.SCH_SITE AS SITE_NAME, a.SCH_ID_SITELINE, c.LINE_NAME AS LINE_NAME, 
b.CUSTOMER_NAME,
b.ORDER_REFERENCE_PO_NO,
b.ORDER_STYLE_DESCRIPTION, b.CUSTOMER_DIVISION, b.ITEM_COLOR_NAME, 
b.ITEM_COLOR_CODE, b.ORDER_PRODUCT_ITEM_TYPE AS PROD_SUBCATEGORY,  
b.ORDER_REFERENCE_PO_NO AS name, DATE_FORMAT(a.SCH_PROD_MONTH, '%M/%Y') ACT_PROD_MONTH,
'' AS AUDITOR_NAME, CURDATE() AS DATE_INSPECTION,
a.SCH_CAPACITY_ID
FROM weekly_prod_schedule a 
LEFT JOIN  viewcapacity b ON b.ID_CAPACITY = a.SCH_CAPACITY_ID
LEFT JOIN zd_item_siteline c ON a.SCH_ID_SITELINE = c.ID_SITELINE
WHERE b.CUSTOMER_NAME = 'PVH' AND c.ZD_STATUS = 1 
AND b.ORDER_REFERENCE_PO_NO LIKE :search 
ORDER BY c.ID_SITELINE`;

export const QueryListDefPvh = `SELECT 
CONCAT(a.DEFECT_INTERNALID, ' - ', a.DEFECT_NAME, ' || ', b.BUYER_DEFECT_CODE, ' - ', b.BUYER_DEFECT_DESCRIPTION) BUYER_DEFECT, 
b.BUYER_CODE, b.DEFECT_INTERNALID, 
b.BUYER_DEFECT_CODE, b.BUYER_DEFECT_DESCRIPTION,
a.DEFECT_INTERNALID, a.DEFECT_NAME
FROM item_defect_internal  a 
LEFT JOIN item_defect_buyer b ON a.DEFECT_INTERNALID = b.DEFECT_INTERNALID
WHERE b.BUYER_CODE = 'PVH'`;
