export const queryGetListOrderHeader = `
SELECT
	oph.ORDER_ID,
	oph.ORDER_TYPE_CODE,
	oph.ORDER_STATUS,
	oph.ORDER_PLACEMENT_COMPANY,
	oph.MANUFACTURING_COMPANY,
	oph.ORDER_REFERENCE_PO_NO,
	oph.ORDER_STYLE_DESCRIPTION,
	oph.ITEM_ID,
	oph.PRODUCT_ID,
	oph.PRICE_TYPE_ID,
	oph.CUSTOMER_ID,
	oph.CUSTOMER_DIVISION_ID,
	oph.CUSTOMER_SEASON_ID,
	oph.CUSTOMER_PROGRAM_ID,
	oph.CUSTOMER_BUYPLAN_ID,
	oph.ORDER_UOM,
	oph.ORDER_QTY,
	oph.ORDER_CONFIRMED_DATE,
	oph.CONTRACT_CONFIRMED_DATE,
	oph.CONTRACT_EXPIRED_DATE,
	oph.CONTRACT_NO,
	oph.PROJECTION_ORDER_ID,
	oph.FLAG_MULTISET_ITEMS,
	oph.SIZE_TEMPLATE_ID,
	oph.CREATE_BY,
	oph.CREATE_DATE,
	oph.UPDATE_BY,
	oph.UPDATE_DATE
FROM
	order_po_header oph
WHERE oph.ORDER_STATUS= :orderStatus
    `;