import { DataTypes } from "sequelize";
import { dbSPL } from "../../config/dbAudit.js";

export const SumbiriPelamar =  dbSPL.define('sumbiri_pelamar', {
  NikKTP: { type: DataTypes.STRING(20), primaryKey: true, allowNull: false },
  PassKey: { type: DataTypes.STRING(100), allowNull: false },
  FullName: { type: DataTypes.STRING(100), allowNull: true },
  Position: { type: DataTypes.STRING(50), allowNull: true },
  BirthPlace: { type: DataTypes.STRING(50), allowNull: true },
  BirthDate: { type: DataTypes.DATEONLY, allowNull: true },
  Phone: { type: DataTypes.STRING(20), allowNull: true },
  Email: { type: DataTypes.STRING(100), allowNull: true },
  AddressIdProv: { type: DataTypes.STRING(10), allowNull: true },
  AddressIdKabKota: { type: DataTypes.STRING(10), allowNull: true },
  AddressIdKecamatan: { type: DataTypes.STRING(10), allowNull: true },
  AddressKTPRT: { type: DataTypes.STRING(10), allowNull: true },
  AddressKTPRW: { type: DataTypes.STRING(10), allowNull: true },
  ALAMATKTP_DETAIL: { type: DataTypes.TEXT, allowNull: true },
  isKTPCurrent: { type: DataTypes.BOOLEAN, allowNull: true },
  AddressIdProvTgl: { type: DataTypes.STRING(10), allowNull: true },
  AddressIdKabKotaTgl: { type: DataTypes.STRING(10), allowNull: true },
  AddressIdKecamatanTgl: { type: DataTypes.STRING(10), allowNull: true },
  AddressCurrentRT: { type: DataTypes.STRING(10), allowNull: true },
  AddressCurrentRW: { type: DataTypes.STRING(10), allowNull: true },
  AddressCurrentDetail: { type: DataTypes.TEXT, allowNull: true },
  BloodType: { type: DataTypes.STRING(2), allowNull: true },
  FatherName: { type: DataTypes.STRING(100), allowNull: true },
  FatherJob: { type: DataTypes.STRING(50), allowNull: true },
  MotherName: { type: DataTypes.STRING(100), allowNull: true },
  MotherJob: { type: DataTypes.STRING(50), allowNull: true },
  ParentAddress: { type: DataTypes.TEXT, allowNull: true },
  ParentPhone: { type: DataTypes.STRING(20), allowNull: true },
  EduSDName: { type: DataTypes.STRING(100), allowNull: true },
  EduSDYear: { type: DataTypes.STRING(4), allowNull: true },
  EduSDType: { type: DataTypes.STRING(50), allowNull: true },
  EduSMPName: { type: DataTypes.STRING(100), allowNull: true },
  EduSMPType: { type: DataTypes.STRING(50), allowNull: true },
  EduSMPYear: { type: DataTypes.STRING(4), allowNull: true },
  EduSMAName: { type: DataTypes.STRING(100), allowNull: true },
  EduSMAType: { type: DataTypes.STRING(50), allowNull: true },
  EduSMAYear: { type: DataTypes.STRING(4), allowNull: true },
  EduD3Name: { type: DataTypes.STRING(100), allowNull: true },
  EduD3Type: { type: DataTypes.STRING(50), allowNull: true },
  EduD3Year: { type: DataTypes.STRING(4), allowNull: true },
  EduS1Name: { type: DataTypes.STRING(100), allowNull: true },
  EduS1Type: { type: DataTypes.STRING(50), allowNull: true },
  EduS1Year: { type: DataTypes.STRING(4), allowNull: true },
  Kursus1Topic: { type: DataTypes.STRING(50), allowNull: true },
  Kursus1Location: { type: DataTypes.STRING(100), allowNull: true },
  Kursus1Periode: { type: DataTypes.STRING(10), allowNull: true },
  Kursus2Topic: { type: DataTypes.STRING(50), allowNull: true },
  Kursus2Location: { type: DataTypes.STRING(100), allowNull: true },
  Kursus2Periode: { type: DataTypes.STRING(10), allowNull: true },
  Work1Name: { type: DataTypes.STRING(100), allowNull: true },
  Work1Position: { type: DataTypes.STRING(50), allowNull: true },
  Work1Place: { type: DataTypes.STRING(50), allowNull: true },
  Work1Periode: { type: DataTypes.STRING(20), allowNull: true },
  Work1Salary: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
  Work2Name: { type: DataTypes.STRING(100), allowNull: true },
  Work2Position: { type: DataTypes.STRING(50), allowNull: true },
  Work2Place: { type: DataTypes.STRING(50), allowNull: true },
  Work2Periode: { type: DataTypes.STRING(20), allowNull: true },
  Work2Salary: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
  Work3Name: { type: DataTypes.STRING(100), allowNull: true },
  Work3Position: { type: DataTypes.STRING(50), allowNull: true },
  Work3Place: { type: DataTypes.STRING(50), allowNull: true },
  Work3Periode: { type: DataTypes.STRING(20), allowNull: true },
  Work3Salary: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
  Org1Name: { type: DataTypes.STRING(100), allowNull: true },
  Org1Position: { type: DataTypes.STRING(50), allowNull: true },
  Org1Periode: { type: DataTypes.STRING(20), allowNull: true },
  Org1Place: { type: DataTypes.STRING(50), allowNull: true },
  Org2Name: { type: DataTypes.STRING(100), allowNull: true },
  Org2Position: { type: DataTypes.STRING(50), allowNull: true },
  Org2Periode: { type: DataTypes.STRING(20), allowNull: true },
  Org2Place: { type: DataTypes.STRING(50), allowNull: true },
  Org3Name: { type: DataTypes.STRING(100), allowNull: true },
  Org3Position: { type: DataTypes.STRING(50), allowNull: true },
  Org3Periode: { type: DataTypes.STRING(20), allowNull: true },
  Org3Place: { type: DataTypes.STRING(50), allowNull: true },
  LikeSports: { type: DataTypes.STRING(50), allowNull: true },
  LikeArts: { type: DataTypes.STRING(50), allowNull: true },
  LikeHobby: { type: DataTypes.STRING(50), allowNull: true },
  LikeVision: { type: DataTypes.STRING(50), allowNull: true },
  SpouseName: { type: DataTypes.STRING(100), allowNull: true },
  Child1Name: { type: DataTypes.STRING(100), allowNull: true },
  Child1Age: { type: DataTypes.INTEGER, allowNull: true },
  Child2Name: { type: DataTypes.STRING(100), allowNull: true },
  Child2Age: { type: DataTypes.INTEGER, allowNull: true },
  Child3Name: { type: DataTypes.STRING(100), allowNull: true },
  Child3Age: { type: DataTypes.INTEGER, allowNull: true },
  Child4Name: { type: DataTypes.STRING(100), allowNull: true },
  Child4Age: { type: DataTypes.INTEGER, allowNull: true },
  CountFamily: { type: DataTypes.INTEGER, allowNull: true },
  SeqFamily: { type: DataTypes.INTEGER, allowNull: true },
  PsikotestPlace: { type: DataTypes.STRING(100), allowNull: true },
  PsikotestTime: { type: DataTypes.STRING(20), allowNull: true },
  ReffName: { type: DataTypes.STRING(100), allowNull: true },
  ReffDept: { type: DataTypes.STRING(50), allowNull: true },
  ReffRelation: { type: DataTypes.STRING(50), allowNull: true },
  ExpectedSalary: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
  ExpectedTMB: { type: DataTypes.STRING(20), allowNull: true },
  isReadyContract: { type: DataTypes.STRING(100), allowNull: true },
  isDocValid: { type: DataTypes.BOOLEAN, allowNull: true },
  isReadyPlacement: { type: DataTypes.BOOLEAN, allowNull: true },
  CreateDate: { type: DataTypes.DATE, defaultValue: DataTypes.NOW }
  }, {
    tableName: 'sumbiri_pelamar',
    timestamps: false,
  });

export const findLamaranByDate = `
SELECT
	NikKTP,
	PassKey,
	FullName,
	Position,
	BirthPlace,
	BirthDate,
	Phone,
	Email,
	AddressIdProv,
	AddressIdKabKota,
	AddressIdKecamatan,
	AddressKTPRT,
	AddressKTPRW,
	ALAMATKTP_DETAIL,
	isKTPCurrent,
	AddressIdProvTgl,
	AddressIdKabKotaTgl,
	AddressIdKecamatanTgl,
	AddressCurrentRT,
	AddressCurrentRW,
	AddressCurrentDetail,
	BloodType,
	FatherName,
	FatherJob,
	MotherName,
	MotherJob,
	ParentAddress,
	ParentPhone,
	EduSDName,
	EduSDYear,
	EduSDType,
	EduSMPName,
	EduSMPType,
	EduSMPYear,
	EduSMAName,
	EduSMAType,
	EduSMAYear,
	EduD3Name,
	EduD3Type,
	EduD3Year,
	EduS1Name,
	EduS1Type,
	EduS1Year,
	Kursus1Topic,
	Kursus1Location,
	Kursus1Periode,
	Kursus2Topic,
	Kursus2Location,
	Kursus2Periode,
	Work1Name,
	Work1Position,
	Work1Place,
	Work1Periode,
	Work1Salary,
	Work2Name,
	Work2Position,
	Work2Place,
	Work2Periode,
	Work2Salary,
	Work3Name,
	Work3Position,
	Work3Place,
	Work3Periode,
	Work3Salary,
	Org1Name,
	Org1Position,
	Org1Periode,
	Org1Place,
	Org2Name,
	Org2Position,
	Org2Periode,
	Org2Place,
	Org3Name,
	Org3Position,
	Org3Periode,
	Org3Place,
	LikeSports,
	LikeArts,
	LikeHobby,
	LikeVision,
	SpouseName,
	Child1Name,
	Child1Age,
	Child2Name,
	Child2Age,
	Child3Name,
	Child3Age,
	Child4Name,
	Child4Age,
	CountFamily,
	SeqFamily,
	PsikotestPlace,
	PsikotestTime,
	ReffName,
	ReffDept,
	ReffRelation,
	ExpectedSalary,
	ExpectedTMB,
	isReadyContract,
	isDocValid,
	isReadyPlacement,
	DATE_FORMAT(CreateDate, '%Y-%m-%d %H:%i:%s') AS CreateDate
FROM
	sumbiri_pelamar
WHERE DATE(CreateDate) = :tglLamaran
`;